project:
  type: website
  execute-dir: project
  output-dir: docs
  resources: [".nojekyll"]

website:
  title: "Group-level effects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  cache: true

